services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9101:9101"
    volumes:
      - /mnt/d/minio-data:/data
    environment:
      MINIO_ROOT_USER: MINIOADMIN
      MINIO_ROOT_PASSWORD: MINIOADMIN
    command: server /data --console-address ":9101"

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jane_db
      MYSQL_USER: john_doe
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --innodb-use-native-aio=0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jane_db
      MYSQL_USER: john_doe
      MYSQL_PASSWORD: password

  valkey:
    image: valkey/valkey
    container_name: valkey
    ports:
      - "6379:6379"
    restart: always

volumes:
  minio_data:
  mysql_data:
