services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "jane_db"
      MYSQL_USER: "john_doe"
      MYSQL_PASSWORD: "password"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "jane_db"
      MYSQL_USER: "john_doe"
      MYSQL_PASSWORD: "password"
